name: Django CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: List directory contents
      run: ls -la
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r demo_github_actions/requirements.txt

    - name: Run tests
      run: python demo_github_actions/manage.py test

  run-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r demo_github_actions/requirements.txt

    - name: Start Django server
      run: python demo_github_actions/manage.py runserver
